// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Fieldslib
//# unitInfo: Requires: Base__Fieldslib
//# shape: Fieldslib:[]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Fieldslib = [0];
   runtime.caml_register_global(0, Fieldslib, "Fieldslib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZmllbGRzbGliLmNtYS5qcyIsInNlY3Rpb25zIjpbeyJvZmZzZXQiOnsibGluZSI6OSwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJmaWVsZHNsaWIuY21hLmpzIiwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCJdLCJzb3VyY2VzQ29udGVudCI6WyIoKiBnZW5lcmF0ZWQgY29kZSAqKSJdLCJuYW1lcyI6WyJydW50aW1lIiwiRmllbGRzbGliIl0sIm1hcHBpbmdzIjoiT0FBQUEsVUFBQSx5QkFBQUMsWUFBQSIsImlnbm9yZUxpc3QiOlswXX19XX0=
