// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Ppx_compare_lib
//# unitInfo: Requires: Base__Ppx_compare_lib
//# shape: Ppx_compare_lib:[F(3),F(3),[],[],N]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    global_data = runtime.caml_get_global_data(),
    Base_Ppx_compare_lib = global_data.Base__Ppx_compare_lib,
    compare_abstract = Base_Ppx_compare_lib[1],
    equal_abstract = Base_Ppx_compare_lib[2],
    Comparable = Base_Ppx_compare_lib[3],
    Equal = Base_Ppx_compare_lib[4],
    Builtin = Base_Ppx_compare_lib[5],
    Ppx_compare_lib =
      [0, compare_abstract, equal_abstract, Comparable, Equal, Builtin];
   runtime.caml_register_global(1, Ppx_compare_lib, "Ppx_compare_lib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X2NvbXBhcmVfbGliLmNtYS5qcyIsInNlY3Rpb25zIjpbeyJvZmZzZXQiOnsibGluZSI6MTAsImNvbHVtbiI6MH0sIm1hcCI6eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X2NvbXBhcmVfbGliLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSIsImdsb2JhbF9kYXRhIiwiQmFzZV9QcHhfY29tcGFyZV9saWIiLCJjb21wYXJlX2Fic3RyYWN0IiwiZXF1YWxfYWJzdHJhY3QiLCJDb21wYXJhYmxlIiwiRXF1YWwiLCJCdWlsdGluIiwiUHB4X2NvbXBhcmVfbGliIl0sIm1hcHBpbmdzIjoiSUFBQUEsVUFBQTtBQUFBLElBQUFDLGNBQUE7QUFBQSxJQUFBQyx1QkFBQTtBQUFBLElBQUFDLG1CQUFBO0FBQUEsSUFBQUMsaUJBQUE7QUFBQSxJQUFBQyxhQUFBO0FBQUEsSUFBQUMsUUFBQTtBQUFBLElBQUFDLFVBQUE7QUFBQSxJQUFBQztBQUFBQSxNQUFBIiwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
