// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Ppx_hash_lib
//# unitInfo: Requires: Base__Ppx_hash_lib
//# shape: Ppx_hash_lib:[[],[]]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    global_data = runtime.caml_get_global_data(),
    Base_Ppx_hash_lib = global_data.Base__Ppx_hash_lib,
    Std = Base_Ppx_hash_lib[1],
    Hashable = Base_Ppx_hash_lib[2],
    Ppx_hash_lib = [0, Std, Hashable];
   runtime.caml_register_global(1, Ppx_hash_lib, "Ppx_hash_lib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X2hhc2hfbGliLmNtYS5qcyIsInNlY3Rpb25zIjpbeyJvZmZzZXQiOnsibGluZSI6MTAsImNvbHVtbiI6MH0sIm1hcCI6eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X2hhc2hfbGliLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSIsImdsb2JhbF9kYXRhIiwiQmFzZV9QcHhfaGFzaF9saWIiLCJTdGQiLCJIYXNoYWJsZSIsIlBweF9oYXNoX2xpYiJdLCJtYXBwaW5ncyI6IklBQUFBLFVBQUE7QUFBQSxJQUFBQyxjQUFBO0FBQUEsSUFBQUMsb0JBQUE7QUFBQSxJQUFBQyxNQUFBO0FBQUEsSUFBQUMsV0FBQTtBQUFBLElBQUFDLGVBQUEiLCJpZ25vcmVMaXN0IjpbMF19fV19
