// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Ppx_log_syntax
//# unitInfo: Requires: Base__Fn, Base__Nothing
//# shape: Ppx_log_syntax:[F(1),N,F(3)*->F(1),[F(1)*,N,F(5)*]]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    global_data = runtime.caml_get_global_data(),
    Base_Nothing = global_data.Base__Nothing,
    Base_Fn = global_data.Base__Fn,
    would_log = Base_Nothing[4],
    default$ = -867743853;
   function message(b, a, param){return Base_Nothing[4];}
   var a = 0, b = Base_Fn[1];
   function would_log$0(c){return b(a, c);}
   function message$0(d, c, b, a, param){return default$;}
   var
    Global = [0, would_log$0, default$, message$0],
    Ppx_log_syntax = [0, would_log, default$, message, Global];
   runtime.caml_register_global(2, Ppx_log_syntax, "Ppx_log_syntax");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X2xvZ19zeW50YXguY21hLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjoxMCwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJwcHhfbG9nX3N5bnRheC5jbWEuanMiLCJzb3VyY2VzIjpbIi9idWlsdGluL2JsYWNrYm94Lm1sIiwiL1VzZXJzL2RzL0RvY3VtZW50cy9wYXRjaHdvcmsvX29wYW0vbGliL3BweF9sb2cvc3ludGF4L3BweF9sb2dfc3ludGF4Lm1sIl0sInNvdXJjZXNDb250ZW50IjpbIigqIGdlbmVyYXRlZCBjb2RlICopIiwib3BlbiEgQmFzZVxuXG50eXBlIHQgPSBOb3RoaW5nLnRcbnR5cGUgdGltZSA9IE5vdGhpbmcudFxudHlwZSByZXR1cm5fdHlwZSA9IFsgYFBweF9sb2dfc3ludGF4X2ltcGxlbWVudGF0aW9uX21pc3NpbmcgXVxuXG5sZXQgd291bGRfbG9nID0gTm90aGluZy51bnJlYWNoYWJsZV9jb2RlXG5sZXQgZGVmYXVsdCA9IGBQcHhfbG9nX3N5bnRheF9pbXBsZW1lbnRhdGlvbl9taXNzaW5nXG5sZXQgbWVzc2FnZSA/bGV2ZWw6XyA/dGltZTpfID90YWdzOl8gPSBOb3RoaW5nLnVucmVhY2hhYmxlX2NvZGVcblxubW9kdWxlIEdsb2JhbCA9IHN0cnVjdFxuICBsZXQgd291bGRfbG9nID0gRm4uY29uc3QgZmFsc2VcbiAgbGV0IGRlZmF1bHQgPSBkZWZhdWx0XG4gIGxldCBtZXNzYWdlID9sZXZlbDpfID90aW1lOl8gP3RhZ3M6XyBfIF8gPSBkZWZhdWx0XG5lbmRcbiJdLCJuYW1lcyI6WyJydW50aW1lIiwiZ2xvYmFsX2RhdGEiLCJCYXNlX05vdGhpbmciLCJCYXNlX0ZuIiwid291bGRfbG9nIiwiZGVmYXVsdCQiLCJtZXNzYWdlIiwicGFyYW0iLCJHbG9iYWwiLCJQcHhfbG9nX3N5bnRheCJdLCJtYXBwaW5ncyI6IklBQUFBLFVBQUE7QUFBQSxJQUFBQyxjQUFBO0FBQUEsSUFBQUMsZUFBQTtBQUFBLElBQUFDLFVBQUE7QUFBQSxJQUFBQyxZQUFBO0FBQUEsSUFBQUMsV0FBQTtBQUFBLFlBQUFDLFFBQUEsTUFBQUMsT0NRdUMsdUJBQXdCO0FBQUEsV0FHL0I7QUFBQSxZQUFBSCxZQUFBLEdBQWQ7QUFBQSxZQUFBRSxVQUFBLFlBQUFDLE9BRTJCLGdCQUFPO0FBQUE7QUFBQSxJQUFBQyxTQUZwQjtBQUFBLElBQUFDLGlCQUFBO0FBQUE7QUFBQTtBQUFBLEVEWGhDIiwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
