// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Variantslib
//# unitInfo: Requires: Base__Variantslib
//# shape: Variantslib:[]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Variantslib = [0];
   runtime.caml_register_global(0, Variantslib, "Variantslib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidmFyaWFudHNsaWIuY21hLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjo5LCJjb2x1bW4iOjB9LCJtYXAiOnsidmVyc2lvbiI6MywiZmlsZSI6InZhcmlhbnRzbGliLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSIsIlZhcmlhbnRzbGliIl0sIm1hcHBpbmdzIjoiT0FBQUEsVUFBQSx5QkFBQUMsY0FBQSIsImlnbm9yZUxpc3QiOlswXX19XX0=
