// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Expect_test_config
//# shape: Expect_test_config:[[F(1)*],F(1),F(1)*,N]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) === 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function return$(x){return x;}
   var IO = [0, return$];
   function sanitize(s){return s;}
   function run(f){return caml_call1(f, 0);}
   var Expect_test_config = [0, IO, run, sanitize, 15023];
   runtime.caml_register_global(0, Expect_test_config, "Expect_test_config");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZXhwZWN0X3Rlc3RfY29uZmlnLmNtYS5qcyIsInNlY3Rpb25zIjpbeyJvZmZzZXQiOnsibGluZSI6OCwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJleHBlY3RfdGVzdF9jb25maWcuY21hLmpzIiwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCIsIi9Vc2Vycy9kcy9Eb2N1bWVudHMvcGF0Y2h3b3JrL19vcGFtL2xpYi9wcHhfZXhwZWN0L2NvbmZpZy9leHBlY3RfdGVzdF9jb25maWcubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiLCJtb2R1bGUgSU8gPSBzdHJ1Y3RcbiAgdHlwZSAnYSB0ID0gJ2FcblxuICBsZXQgcmV0dXJuIHggPSB4XG5lbmRcblxubGV0IHNhbml0aXplIHMgPSBzXG5sZXQgcnVuIGYgPSBmICgpXG5sZXQgdXBvbl91bnJlbGVhc2FibGVfaXNzdWUgPSBgQ1JcbiJdLCJuYW1lcyI6WyJydW50aW1lIiwiY2FtbF9jYWxsMSIsImYiLCJhMCIsInJldHVybiQiLCJ4IiwiSU8iLCJzYW5pdGl6ZSIsInMiLCJydW4iLCJFeHBlY3RfdGVzdF9jb25maWciXSwibWFwcGluZ3MiOiJPQUFBQSxVQUFBO0FBQUEsWUFBQUMsV0FBQUMsR0FBQUM7QUFBQUEsSUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBLFlBQUFDLFFBQUFDLEdDR2lCLFNBQUM7QUFBQSxPQUFBQyxLREhsQjtBQUFBLFlBQUFDLFNBQUFDLEdDTWlCLFNBQUM7QUFBQSxZQUFBQyxJQUFBUCxHQUNOLHVCQUFJO0FBQUEsT0FBQVEscUJEUGhCIiwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
