// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Ppx_stable_witness_runtime
//# shape: Ppx_stable_witness_runtime:[]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Ppx_stable_witness_runtime = [0];
   runtime.caml_register_global
    (0, Ppx_stable_witness_runtime, "Ppx_stable_witness_runtime");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X3N0YWJsZV93aXRuZXNzX3J1bnRpbWUuY21hLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjo4LCJjb2x1bW4iOjB9LCJtYXAiOnsidmVyc2lvbiI6MywiZmlsZSI6InBweF9zdGFibGVfd2l0bmVzc19ydW50aW1lLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSIsIlBweF9zdGFibGVfd2l0bmVzc19ydW50aW1lIl0sIm1hcHBpbmdzIjoiT0FBQUEsVUFBQSx5QkFBQUMsNkJBQUEiLCJpZ25vcmVMaXN0IjpbMF19fV19
