// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Inline_test_config
//# shape: Inline_test_config:[F(1)*]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function pre_test_hook(a){return 0;}
   var Inline_test_config = [0, pre_test_hook];
   runtime.caml_register_global(0, Inline_test_config, "Inline_test_config");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5saW5lX3Rlc3RfY29uZmlnLmNtYS5qcyIsInNlY3Rpb25zIjpbeyJvZmZzZXQiOnsibGluZSI6OCwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJpbmxpbmVfdGVzdF9jb25maWcuY21hLmpzIiwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCJdLCJzb3VyY2VzQ29udGVudCI6WyIoKiBnZW5lcmF0ZWQgY29kZSAqKSJdLCJuYW1lcyI6WyJydW50aW1lIiwicHJlX3Rlc3RfaG9vayIsIklubGluZV90ZXN0X2NvbmZpZyJdLCJtYXBwaW5ncyI6Ik9BQUFBLFVBQUE7QUFBQSxZQUFBQyxjQUFBO0FBQUEsT0FBQUMscUJBQUEiLCJpZ25vcmVMaXN0IjpbMF19fV19
