// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Ppx_quickcheck_runtime__
//# shape: Ppx_quickcheck_runtime__:[[]]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    Ppx_quickcheck_runtime = [0],
    Ppx_quickcheck_runtime$0 = [0, Ppx_quickcheck_runtime];
   runtime.caml_register_global
    (0, Ppx_quickcheck_runtime$0, "Ppx_quickcheck_runtime__");
   return;
  }
  (globalThis));

//# unitInfo: Provides: Ppx_quickcheck_runtime__Quickcheckable
//# shape: Ppx_quickcheck_runtime__Quickcheckable:[]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    Ppx_quickcheck_runtime_Quickch = [0];
   runtime.caml_register_global
    (0,
     Ppx_quickcheck_runtime_Quickch,
     "Ppx_quickcheck_runtime__Quickcheckable");
   return;
  }
  (globalThis));

//# unitInfo: Provides: Ppx_quickcheck_runtime
//# shape: Ppx_quickcheck_runtime:[]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Ppx_quickcheck_runtime = [0];
   runtime.caml_register_global
    (0, Ppx_quickcheck_runtime, "Ppx_quickcheck_runtime");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X3F1aWNrY2hlY2tfcnVudGltZS5jbWEuanMiLCJzZWN0aW9ucyI6W3sib2Zmc2V0Ijp7ImxpbmUiOjksImNvbHVtbiI6MH0sIm1hcCI6eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHB4X3F1aWNrY2hlY2tfcnVudGltZS5jbWEuanMiLCJzb3VyY2VzIjpbIi9idWlsdGluL2JsYWNrYm94Lm1sIl0sInNvdXJjZXNDb250ZW50IjpbIigqIGdlbmVyYXRlZCBjb2RlICopIl0sIm5hbWVzIjpbInJ1bnRpbWUiLCJQcHhfcXVpY2tjaGVja19ydW50aW1lIl0sIm1hcHBpbmdzIjoiSUFBQUEsVUFBQTtBQUFBLElBQUFDLHlCQUFBO0FBQUEsSUFBQUEsMkJBQUEiLCJpZ25vcmVMaXN0IjpbMF19fSx7Im9mZnNldCI6eyJsaW5lIjoyNCwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiJwcHhfcXVpY2tjaGVja19ydW50aW1lLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSIsIlBweF9xdWlja2NoZWNrX3J1bnRpbWVfUXVpY2tjaCJdLCJtYXBwaW5ncyI6IklBQUFBLFVBQUE7QUFBQSxJQUFBQyxpQ0FBQSIsImlnbm9yZUxpc3QiOlswXX19LHsib2Zmc2V0Ijp7ImxpbmUiOjM5LCJjb2x1bW4iOjB9LCJtYXAiOnsidmVyc2lvbiI6MywiZmlsZSI6InBweF9xdWlja2NoZWNrX3J1bnRpbWUuY21hLmpzIiwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCJdLCJzb3VyY2VzQ29udGVudCI6WyIoKiBnZW5lcmF0ZWQgY29kZSAqKSJdLCJuYW1lcyI6WyJydW50aW1lIiwiUHB4X3F1aWNrY2hlY2tfcnVudGltZSJdLCJtYXBwaW5ncyI6Ik9BQUFBLFVBQUEseUJBQUFDLHlCQUFBIiwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
