// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cma, use-js-string=true, version=6.2.0

//# unitInfo: Provides: Base_internalhash_types
//# shape: Base_internalhash_types:[]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Base_internalhash_types = [0];
   runtime.caml_register_global
    (0, Base_internalhash_types, "Base_internalhash_types");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYmFzZV9pbnRlcm5hbGhhc2hfdHlwZXMuY21hLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjo4LCJjb2x1bW4iOjB9LCJtYXAiOnsidmVyc2lvbiI6MywiZmlsZSI6ImJhc2VfaW50ZXJuYWxoYXNoX3R5cGVzLmNtYS5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSIsIkJhc2VfaW50ZXJuYWxoYXNoX3R5cGVzIl0sIm1hcHBpbmdzIjoiT0FBQUEsVUFBQSx5QkFBQUMsMEJBQUEiLCJpZ25vcmVMaXN0IjpbMF19fV19
